# Generated by Django 3.2.6 on 2021-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20210822_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='stutus',
            field=models.CharField(choices=[('accepted', 'accepted'), ('packed', 'packed'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('cancel', 'cancel')], default='pending', max_length=70),
        ),
    ]
