# Generated by Django 3.2.6 on 2021-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_alter_order_placed_stutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
